blog/blog/urls.py
from django.urls import path
from blog import cb_views    # ⭐ 핵심 변경
from blog import  views 
app_name = 'blog'

urlpatterns = [
    path('', cb_views.BlogListView.as_view(), name='list'),
    path('create/', cb_views.BlogCreateView.as_view(), name='create'),
    path('<int:blog_pk>/', cb_views.BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', cb_views.BlogUpdateView.as_view(), name='update'),
    #path('<int:pk>/update/', views.blog_update, name='update'),
    path('<int:pk>/delete/', cb_views.BlogDeleteView.as_view(), name='delete'),
    path('comment/create/<int:blog_pk>/',cb_views.CommentCreateView.as_view(),name='comment_create'),
]

blog/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView, RedirectView, View
from django.shortcuts import render, redirect
from django.conf import settings
from django.conf.urls.static import static

from blog import views,cb_views
from blog.views import blog_list
from blog.cb_views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
)

from member import views as member_views


#class AboutView(TemplateView):
    #template_name = "about.html"


#class TestView(View):
    #def get(self, request):
        #return render(request, "test_get.html")
    
    #def post(self, request):
        #return render(request, 'test_post.html')




urlpatterns = [
    path("admin/", admin.site.urls),

        # blog
    path('',include('blog.urls')),
        
    # auth
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/", member_views.sign_up, name="signup"),
    path("login/", member_views.login, name="login"),
    path('summernote/', include('django_summernote.urls')),




    #FBV Blog
    # blog
    #path("", views.blog_list, name="blog_list"),
    #path("create/", views.blog_create, name="blog_create"),
    #path("<int:pk>/", views.blog_detail, name="blog_detail"),
    #path("<int:pk>/update/", views.blog_update, name="blog_update"),
    #path("<int:pk>/delete/", views.blog_delete, name="blog_delete"),

    #CBV Blog
    #path('' , cb_views.BlogListView.as_view(), name='blog_list'),
    #path('<int:pk>/', cb_views.BlogDetailView.as_view(), name='blog_detail'),
    #path('create/', cb_views.BlogCreateView.as_view(), name='blog_create'),
    #path('<int:pk>/update/',cb_views.BlogUpdateView.as_view(),name ='blog_update'),
    #path('<int:pk>/delete/',cb_views.BlogDeleteView.as_view(),name ='blog_delete'),

    #path('about/',TemplateView.as_view(template_name='about.html'),name='about'),
    #path('about/',AboutView.as_view(), name='about'),
    #path('redirect/',RedirectView.as_view(pattern_name = 'about'),name = 'redirect'),
    #path('test/', TestView.as_view(), name='test' )
    ]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

config/urls.py
# studycalender/config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

from .views import RootView, APIRootView


# --------------------------------------------------
# API DOCUMENTATION
# --------------------------------------------------
docs_urlpatterns = [
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

# --------------------------------------------------
# URL PATTERNS
# --------------------------------------------------
urlpatterns = [
    # Root
    path("", RootView.as_view(), name="root"),

    # API Root
    path("api/", APIRootView.as_view(), name="api-root"),

    # Admin
    path("admin/", admin.site.urls),

    # ---------------------------
    # API - Apps
    # ---------------------------
    path("api/users/", include("apps.users.urls")),
    path("api/calendars/", include("apps.calendars.urls")),
    path("api/study/", include("apps.study.urls")),
    path("api/reports/", include("apps.reports.urls")),

    # ---------------------------
    # Browsable API (Session Auth)
    # ---------------------------
    path("api/auth-session/", include("rest_framework.urls")),
]

# API Docs
urlpatterns += docs_urlpatterns

# Media (DEV only)
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

guguden/config/urls.py
"""
✅ 이 파일은 "Django가 요청을 받았을 때 어떤 함수를 실행할지(라우팅)" + "그 함수가 무엇을 응답할지(view)"
를 한 곳에 모아둔 예시 코드다.

📌 Django 동작 큰 흐름
1) 브라우저가 URL로 요청 보냄  (예: GET /movie/ )
2) Django는 ROOT_URLCONF(보통 config/settings.py에 설정된 urls.py)를 읽음
3) urlpatterns에서 요청 URL과 일치하는 path를 찾음
4) 매칭된 path에 연결된 view 함수(index, movies 등)를 실행
5) view 함수가 HttpResponse를 리턴하면, 그게 브라우저 화면에 그대로 표시됨
"""
from django.http import HttpResponse, Http404
from django.contrib import admin
from django.urls import path
from django.shortcuts import render


movie_list = [
    {'title': '귀멸의 칼날', 'director': 'ufotable'},
    {'title': '주토피아 2', 'director': 'Disney'},
    {'title': '사무라이 참프루', 'director': 'Manglobe'},
    {'title': '허니와 클로버', 'director': 'J.C.STAFF'},
]


def index(request):
    return HttpResponse('hello?')


def book_list(request):
    #book_text = ''
    #for i in range(10):
        #book_text += f'book{i}<br>'
    return render(request,'book_list.html',{'range': range(0,10)})


def book(request, num):
    return render(request,'book_detali.html',{'num':num})


def language(request, lang):
    return HttpResponse(f'<h1>{lang} 언어 페이지 입니다.</h1>')


def python(request):
    return HttpResponse('python 페이지 입니다.')


def movies(request):
    return render(
        request,
        'movies.html',
        {'movie_list':movie_list}
        )


def movie_detail(request, index):
    if index > len(movie_list) - 1:
        raise Http404

    movie = movie_list[index]

    context = {
        'movie_list': movie_list, 
        'index': index}

    return render(request,'movie.html',context)

def gugu(request, num) : 

    context =  {
        'num': num,
        'results' : [num * i for i in range(1,10)]
    }
    return render(
        request,
        'gugu.html',
        context )



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('book_list/', book_list),
    path('book_list/<int:num>/', book),
    path('language/python/', python),
    path('language/<str:lang>/', language),
    path('movie/', movies),
    path('movie/<int:index>/', movie_detail),
    path('gugu/<int:num>/', gugu),
]

blog/blog/models.py
from io import BytesIO
from pathlib import Path
import re
from PIL import Image

from django.conf import settings
from django.core.files import File
from django.db import models
from django.urls import reverse

from utils.model import TimestampModel


class Blog(TimestampModel):
    CATEGORY_CHOICES = (
        ("FREE", "자유게시판"),
        ("EMOTION", "감성글귀"),
    )

    category = models.CharField(
        "카테고리",
        max_length=10,
        choices=CATEGORY_CHOICES,
        default="FREE",
    )
    title = models.CharField("제목", max_length=100)
    content = models.TextField("본문")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="작성자",
        related_name="blogs",
    )
    image =models.ImageField('이미지', null=True, blank=True,upload_to='blog/%Y/%m/%d')
    thubnail = models.ImageField("썸네일",null=True, blank=True, upload_to='blog/%Y/%m/%d')

    def __str__(self):
        return f"[{self.get_category_display()}] {self.title[:10]}"

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"blog_pk": self.pk})

    def get_thumbnail_image_url(self):
        if self.thumbnail:
            return self.thumbnail.url
        if self.image:
            return self.image.url
        return None

    
   # def save(self,*args,**kwargs):
        #if not self.image:
            #return super(self, *args, **kwargs)

        #image =  Image.open(self.image)
        #image.thumbnail((300,300))     
        #image_path = Path(self.imge.name)
        #thumbnail_name = image_path.stem
        #thumbnail_extension = image_path.suffix
        #thumbnail_filename = f"{thumbnail_name}_thumb{thumbnail_extension}" #databases
        #if thumbnail_extension in ['.jpg','jpeg']:
            #file_type = 'JPEG'
        #elif thumbnail_extension == '.gif':
            #file_type = 'GIF'
        #elif thumbnail_extension == '.png':
            #file_type = 'PNG' 
        #else:
            #return super().save(*args,**kwargs)
        #temp_thmb = BytesIO()
        #image.save(temp_thmb, file_type)
        #temp_thmb.seek(0)
        #self.thumbnail.save(thumbnail_filename,temp_thmb,seve=False)
        #return super().save(*args,**kwargs)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.image:
            return

        img = Image.open(self.image)
        img.thumbnail((300, 300))

        image_path = Path(self.image.name)
        ext = image_path.suffix.lower()
        thumb_name = f"{image_path.stem}_thumb{ext}"

        thumb_io = BytesIO()

        if ext in [".jpg", ".jpeg"]:
            img.save(thumb_io, format="JPEG")
        elif ext == ".png":
            img.save(thumb_io, format="PNG")
        elif ext == ".gif":
            img.save(thumb_io, format="GIF")
        else:
            return

        thumb_io.seek(0)

        self.thumbnail.save(
            thumb_name,
            File(thumb_io),
            save=False
        )

        super().save(update_fields=["thumbnail"])




    class Meta:
        verbose_name = "블로그"
        verbose_name_plural = "블로그 목록"


class Comment(TimestampModel):
    blog = models.ForeignKey(
        Blog,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="블로그",
    )
    content = models.CharField("본문", max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="작성자",
    )

    def __str__(self):
        return f"{self.blog.title} 댓글"

    def get_urlabsolute_url(self):
        return reverse('blog:detail', kwargs={'blog_pk':self.pk})



    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 목록"
        ordering = ('-created_at', '-id')


# models.CASEDE = 같이 삭제
# models.PROTECT = 삭제가 불가능함 (유저가 삭제 하려고 할때 블로그가 있으면 유저 삭제가 불가능)
# models.SET_NULL = NULL값을 넘습니다 (유저 삭제시 블로그가 auth가 null값이 됨)

# 익명,기존사용자 허용
# author = models.ForeignKey(
# settings.AUTH_USER_MODEL,
# on_delete=models.SET_NULL,
# null=True,
# blank=True,
# verbose_name="작성자",
# related_name="blogs"
# )

# mysql로 봤을때 생성되는 테이블
# CREATE TABLE blog_blog (
# id BIGINT AUTO_INCREMENT PRIMARY KEY,
# category VARCHAR(10) NOT NULL,
# title VARCHAR(100) NOT NULL,
# content LONGTEXT NOT NULL,
# created_at DATETIME(6) NOT NULL,
# updated_at DATETIME(6) NOT NULL
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


# =========================
# 문자열 표현 (선택)
# =========================
# Admin / Shell에서 객체를 문자열로 볼 때 사용
# def __str__(self):
# return f"[{self.category}] {self.title}"

blog/member/models.py
from django.db import models

# Create your models here.

blog/blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import Blog, Comment


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        # fields = "__all__"
        fields = ("title", "content", "category", "image")  
        widgets = {
            # ✅ Summernote 적용
            "content": SummernoteWidget(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        widgets = {
            # ❌ TextInput + rows → 오류
            # ✅ Textarea 사용
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                    "placeholder": "댓글을 입력하세요",
                }
            )
        }
        labels = {
            "content": "댓글",
        }

blog/blog/views.py
# ==================== 상세 주석 및 코드 설명 ====================
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.db.models import Q

from blog.forms import BlogForm
from .models import Blog

def blog_list(request):
    blogs = Blog.objects.all().order_by("created_at")
    qwer = request.GET.get("qwer")
    if qwer:
        blogs = blogs.filter(
            Q(title__icontains=qwer) |
            Q(content__icontains=qwer) |
            Q(author__username__icontains=qwer)
        )
    paginator = Paginator(blogs, 10)
    page = request.GET.get("page")
    page_object = paginator.get_page(page)
    context = {
        "object_list": page_object.object_list,
        "page_object": page_object,
    }
    return render(request, "blog_list.html", context)

def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    context = {
        "test": "TEST",
        "blog": blog,
    }
    return render(request, "blog_detail.html", context)

@login_required()
def blog_create(request):
    form = BlogForm(request.POST or None)
    if form.is_valid():
        blog = form.save(commit=False)
        blog.author = request.user
        blog.save()
        return redirect(reverse("blog_detail", kwargs={"blog_pk": blog.pk}))
    context = {
        "form": form,
    }
    return render(request, "blog_form.html", context)

@login_required()
def blog_update(request, pk):
    if request.user.is_superuser:
        blog = get_object_or_404(Blog, pk=pk)
    else:
        blog = get_object_or_404(Blog, pk=pk, author=request.user)

    form = BlogForm(
        request.POST or None,
        request.FILES or None,
        instance=blog
    )

    if form.is_valid():
        blog = form.save()
        return redirect(reverse("blog:detail", kwargs={"blog_pk": blog.pk}))

    return render(request, "blog_form.html", {
        "blog": blog,
        "form": form,
    })

@login_required()
@require_http_methods(["POST"])
def blog_delete(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    blog.delete()
    return redirect(reverse("blog_list"))

blog/member/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout

def sign_up(request):
    """
    회원가입(sign up) 뷰
    - POST 요청이면 전송된 폼 데이터를 바탕으로 UserCreationForm을 생성한다.
    - form이 유효할 때:
        1. form.save()로 새 사용자 객체를 저장
        2. 새 사용자를 로그인(django_login) 처리하여 세션에 등록
        3. 로그인이 끝나면 settings.LOGIN_REDIRECT_URL로 리디렉트
    - form이 유효하지 않거나 GET 요청일 때:
        1. (request.POST or None)으로 빈 폼 혹은 에러 포함 폼을 생성
        2. 회원가입 페이지(templates/registration/signup.html)에 form을 넘겨 렌더링
    """
    form = UserCreationForm(request.POST or None)  # POST 데이터로 폼 생성(없으면 빈 폼)
    if form.is_valid():  # 폼 유효성 검사
        user = form.save()  # 새 사용자를 DB에 저장
        django_login(request, user)  # 방금 만든 사용자로 바로 로그인
        return redirect(settings.LOGIN_REDIRECT_URL)  # 로그인 후 이동
    return render(request, "registration/signup.html", {"form": form})  # 폼과 함께 회원가입 페이지 렌더

def login(request):
    """
    로그인(login) 뷰
    - POST라면, 사용자가 제출한 데이터를 AuthenticationForm에 담는다.
    - form이 유효하면:
        1. get_user()로 인증된 사용자 객체 추출
        2. 해당 사용자로 로그인(django_login)
        3. redirect_to: 로그인 전 가려고 했던 페이지가 있으면 그리로, 없으면 LOGIN_REDIRECT_URL로 리디렉트
    - GET이라면, 빈 AuthenticationForm 생성
    - 로그인 템플릿(templates/registration/login.html)에 form을 넘겨 렌더링
    """
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)  # POST 데이터로 폼 생성
        if form.is_valid():  # 폼 유효성 검사(아이디/비밀번호 검증)
            user = form.get_user()  # 인증된 유저 정보 가져오기
            django_login(request, user)  # 해당 유저로 로그인(session 등록)
            redirect_to = request.GET.get("next")  # 로그인 직전 원래 가고 싶었던 URL(없으면 None)
            if redirect_to:
                return redirect(redirect_to)  # "next" 값이 있다면 해당 URL로 리디렉트
            return redirect(settings.LOGIN_REDIRECT_URL)  # 아니면 설정된 기본 경로로
    else:
        form = AuthenticationForm(request)  # GET 요청: 빈 로그인 폼 생성
    return render(
        request,
        "registration/login.html",
        {"form": form},
    )

def logout(request):
    """
    로그아웃(logout) 뷰
    - django_logout 함수로 현 사용자를 로그아웃(세션 데이터 제거)
    - 로그아웃 후 설정된 LOGIN_REDIRECT_URL로 리디렉트
    """
    django_logout(request)  # 세션에서 사용자 정보 제거 = 로그아웃
    return redirect(settings.LOGIN_REDIRECT_URL)  # 로그아웃 후 지정된 페이지로 이동

blog/templates/_blog_update.html
{% extends 'base.html' %}

{% block content %}

<div style="display: flex; justify-content: space-between; align-items: center;">
    <h1>블로그 수정</h1>
    <button form="update-form" type="submit">수정</button>
</div>

<form id="update-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
</form>

{% endblock content %}

blog/templates/about.html
<!-- 
    이 파일은 about.html로, 웹사이트의 'About'(소개) 페이지를 담당합니다.
    이 HTML은 정적 페이지로, 서버에서 클라이언트(브라우저)에게 제공되어 사용자가 볼 수 있습니다.
    Django 템플릿에서 확장하지 않고 독립적으로 HTML 구조를 정의합니다.
-->

<!DOCTYPE html> <!-- 문서의 타입을 HTML5로 지정. 브라우저가 최신 HTML 해석하도록 안내 -->
<html lang="en"> <!-- 페이지의 주 언어를 영어로 지정 (lang="ko"로 변경 가능)-->
<head>
    <!-- meta charset: 웹 페이지 문자 인코딩을 UTF-8로 지정 (한글 등 다양한 문자 지원) -->
    <meta charset="UTF-8">

    <!-- meta viewport: 모바일이나 다양한 장치에서 화면 크기 자동 조정 -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- title: 브라우저 탭/검색창에 표시될 제목 -->
    <title>Document</title>
</head>
<body>
    <!-- 메인 제목 영역: 실제 화면에 가장 크고 강조된 글씨로 노출됨 -->
    <h1>어바웃 페이지 입니다.</h1>
    <!--
        이 영역에 사이트/서비스의 소개글, 팀 정보, 서비스 목적 등
        구체적인 "About" 내용을 추가할 수 있습니다.
    -->
</body>
</html>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>블로그 프로젝트</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    {% block extra_head %}{% endblock %}
</head>
<body>

<nav class="d-flex justify-content-between py-2 px-4 bg-black text-white">
    <div>
        <a class="text-decoration-none text-white" href="{% url 'blog:list' %}">홈</a>
    </div>

    <div style="text-align: right;">
        {% if request.user.is_authenticated %}
            <form action="{% url 'logout' %}" method="POST" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm">로그아웃</button>
            </form>
            {{ request.user.username }}
        {% else %}
            <a href="{% url 'signup' %}">회원가입</a>
            <a href="{% url 'login' %}">로그인</a>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer>
</footer>

<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
{% block js %}{% endblock %}

</body>
</html>

blog/templates/blog_create.html
{% extends 'base.html' %}
{% block content %}
<h1>블로그 작성</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">생성</button>
{% endblock content %}



blog/templates/blog_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-2 d-flex justify-content-between">
    <h1 class="text-center mt-2">{{ object.title }}</h1>

    {% if request.user == object.author or request.user.is_superuser %}
    <div>
        {{ object.author.username }}
        <a class="btn btn-sm btn-warning" href="{% url 'blog:update' object.pk %}">
            수정
        </a>
        <form id="delete_form"
              action="{% url 'blog:delete' object.pk %}"
              method="post"
              style="display:inline;">
            {% csrf_token %}
            <button type="button"
                    id="delete_btn"
                    class="btn btn-sm btn-danger">
                삭제
            </button>
        </form>
    </div>
    {% endif %}
</div>

<hr>
{% if blog.image %}
<img src="{{ blog.imge.url }}" alt="" class="w-100">
{% endif %}
<!-- 본문 (HTML 포함 렌더링) -->
<p>{{ object.content|safe }}</p>

<hr>

{% if request.user.is_authenticated %}
<form method="post"
      action="{% url 'blog:comment_create' object.pk %}"
      class="d-flex align-items-center gap-2"
      style="width: 100%; max-width: 1300px;">
    {% csrf_token %}
    <div class="input-group">
        {{ comment_form.content }}
        <button class="btn btn-primary" type="submit">
            작성
        </button>
    </div>
</form>
{% endif %}

<hr>

<div class="mb-2" id="comment_wrapper">
    {% for comment in object.comments.all %}
    <div class="border-bottom py-2">
        {{ comment.content }}
        <p class="text-end mb-1">
            <small>
                {{ comment.author.username }} |
                {{ comment.created_at|date:'Y-m-d H:i' }}
            </small>
        </p>
    </div>
    {% empty %}
        <p>아직 댓글이 없습니다.</p>
    {% endfor %}
</div>

{% include 'pagination.html' with fragment='comment_wrapper' %}

<a class="btn btn-sm btn-info mt-2" href="{% url 'blog:list' %}">
    목록
</a>

<script>
    const deleteBtn = document.querySelector('#delete_btn');
    if (deleteBtn) {
        deleteBtn.addEventListener('click', function () {
            if (confirm('삭제 하시겠습니까?')) {
                document.querySelector('#delete_form').submit();
            }
        });
    }
</script>
{% endblock %}

blog/templates/blog_form.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mt-2">블로그 {{ sub_title }}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary">
        {% if btn_name %}
            {{ btn_name }}
        {% else %}
            저장
        {% endif %}
    </button>
</form>
{% endblock %}

{% block js %}
{% include 'form_js.html' %}
{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-2 text-center">
    <h1 class="d-inline">블로그 목록</h1>
    <a href="{% url 'blog:create' %}" class="float-end btn btn-sm btn-primary">생성</a>
</div>

<hr>

<form method="get" style="margin-bottom: 10px;">
    <input class="form-control-sm"
           name="qwer"
           type="text"
           placeholder="검색어를 입력하세요"
           value="{% if request.GET.qwer %}{{ request.GET.qwer }}{% endif %}">
    <button class="btn btn-sm btn-info ms-1">검색</button>
</form>

{% for blog in object_list %}
<div class="my-1">
    <a href="{% url 'blog:detail' blog.pk %}"
       class="link-primary link-underline-opacity-0 link-underline-opacity-100-hover row">
       
       {% if blog.thumbnail %}
       <img src="{{ blog.thumbnail.url }}" alt="" class="col-2">
       {% elif blog.image %}
       <img src="{{ blog.image.url }}" alt="" class="col-2">
       {% endif %}

        <span class="col-10">
            [{{ blog.get_category_display }}] {{ blog.title }} -
            <small>{{ blog.created_at|date:"Y-m-d" }}</small>
        </span>

    </a>
</div>
{% endfor %}

{% include 'pagination.html' %}
{% endblock %}

blog/templates/blog_update.html
{% extends 'base.html' %}

{% block content %}

<div style="display: flex; justify-content: space-between; align-items: center;">
    <h1>블로그 수정</h1>
    <button form="update-form" type="submit">수정</button>
</div>

<form id="update-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
</form>

{% endblock content %}

blog/templates/form_js.html
<script>
    document.querySelectorAll('select, input, textarea').forEach(function (ele) {
        ele.classList.add('form-control');
    });
</script>

blog/templates/test_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test_GET</title>
</head>
<body>
    <h1>Test_GET페이지 입니다</h1>
    <form method="post">
        {% csrf_token %}
        <button>post</button>
    </form>
</body>
</html>

blog/templates/test_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test_POST</title>
</head>
<body>
    <h1>Test_POST페이지 입니다.</h1>
</body>
</html>